## 科学计算之NumPy
NumPy（Numerical Python）是一个开源的Python科学计算库，它是python科学计算库的基础库。这个库的前身是1995年就开始开发的一个用于数组运算的库。经过长时间的发展，基本上已经成为绝大部分Python科学计算的基础包。

---
### 1 模块导入

##### （1）导入numpy模块
使用import语句导入numpy模块。 

下句为导入numpy模块代码惯例。

In [81]:
import numpy as np

---
### 2 数据创建

#### 2.1 常规创建方式

##### （2）np.array()函数
使用numpy中array函数将可迭代对象转化为ndarray类型以备后续计算。

In [82]:
a = np.array(range(4))                        # 生成ndarray
a

array([0, 1, 2, 3])

##### （3）np.arange()函数
使用numpy中arange函数直接生成ndarray数据，运算逻辑类似range()内置函数。

np.arange(n)返回一个可产生从0到n（不含n），步长为1数字的ndarray.  
np.arange(a, b, s)返回一个可产生从a到b（不含b），步长为s数字的ndarray.

In [83]:
b = np.arange(5)
b

array([0, 1, 2, 3, 4])

#### 2.2 创建特殊ndarray

##### （4）np.zeros
生成一个形状如传入参数，元素均为0的ndarray。

In [84]:
a = np.zeros((3,3))
a

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

##### （5）np.ones
生成一个形状如传入参数，元素均为1的ndarray。


In [85]:
a = np.ones((3,3))
a

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

##### （6）np.random模块
利用该模块内的函数生成形状如传入参数，元素符合对应分布的ndarray。

常用np.random.randn(a)生成a\*1的ndarray，其值符合正态分布。
（该模块内其他函数可在ipython中运行dir(np.random)进行查看）

In [86]:
a = np.random.randn(3)
a

array([ 0.87057995,  1.6873523 ,  0.54767621])

---
### 3 数学运算

#### 3.1 基本运算 

##### （7）求绝对值
使用np.abs函数对ndarray中每一个元素求绝对值。

In [87]:
a = np.array([1, -2, 3, -4])                             # 创建ndarray

np.abs(a)                                                # 求绝对值    

array([1, 2, 3, 4])

##### （8）求平方根
使用np.sqrt函数对ndarray中每个元素求平方根。

In [88]:
a = np.array([1, 2, 3, 4])                               # 创建ndarray

np.sqrt(a)                                               # 求平方根    

array([ 1.        ,  1.41421356,  1.73205081,  2.        ])

##### （9）求指数幂
使用np.exp函数对ndarray中每个元素求指数幂

In [89]:
a = np.array([1, 2, 3, 4])                               # 创建ndarray

np.exp(a)                                               # 求指数幂    

array([  2.71828183,   7.3890561 ,  20.08553692,  54.59815003])

##### （10）求自然对数
使用np.log函数对ndarray中每个元素求自然对数。

In [90]:
a = np.array([1, 2, 3, 4])                               # 创建ndarray

np.log(a)                                                # 求自然对数    

array([ 0.        ,  0.69314718,  1.09861229,  1.38629436])

##### （11）返回符号
使用np.sign函数对ndarray中每个元素的符号进行判断。其中，对应正数返回1，对应负数返回-1，对应0返回0。

In [91]:
a = np.array([1, -2, 0])                                # 创建ndarray

np.sign(a)                                              # 求符号

array([ 1, -1,  0])

#### 3.2 聚合运算

##### （12）求最大值
np.max函数与array.max方法等价。

In [92]:
a = np.array([1, -2, 0])                                # 创建ndarray

a.max()                                                 # 求最大值

1

##### （13）求最大值索引
返回ndarray元素中最大元素的位置索引。

np.argmax函数与array.argmax方法等价。

In [93]:
a = np.array([1, -2, 0])                                # 创建ndarray

a.argmax()                                              # 求最大值索引

0

##### （14）求最小值
np.min函数与array.min方法等价。

In [94]:
a = np.array([1, -2, 0])                                # 创建ndarray

a.min()                                                 # 求最小值    

-2

##### （15）求最小值索引
np.argmin函数与array.argmin方法等价。

In [95]:
a = np.array([1, -2, 0])                                # 创建ndarray

a.argmin()                                              # 求最小值索引

1

##### （16）求和
np.sum函数与array.sum方法等价。

In [96]:
a = np.array([1, -2, 0])                                # 创建ndarray

a.sum()                                                 # 求和

-1

##### （17）求积
np.prod函数和array.prod方法等价。

In [97]:
a = np.array([1, -2, 0])                                # 创建ndarray

a.prod()                                                # 求积    

0

##### （18）求均值
np.mean函数与array.mean方法等价。

In [98]:
a = np.array([1, -2, 0])                                # 创建ndarray

a.mean()                                                # 求均值

-0.33333333333333331

##### （19）求中位数
返回沿特定轴的中位数。

In [99]:
a = np.array([1, -2, 0])                                # 创建ndarray

np.median(a)                                            # 求中位数

0.0

##### （20）求标准差
返回沿特定轴的标准差。

np.std函数与array.std方法等价。

In [100]:
a = np.array([1, -2, 0])                                # 创建ndarray

a.std()                                                 # 求标准差

1.247219128924647

##### （21）求方差
返回沿特定轴的方差。

np.var函数与array.var方法等价。

In [101]:
a = np.array([1, -2, 0])                                # 创建ndarray

a.var()                                                 # 计算方差

1.5555555555555554

### 3.3 累计运算

##### （22）累计和
np.cumsum函数与array.cumsum方法等价。

In [102]:
a = np.array([1, -2, 0])                                # 创建ndarray

a.cumsum()                                              # 计算累计和

array([ 1, -1, -1], dtype=int32)

##### （23）累积乘积
np.cumprod函数与array.cumprod方法等价。

In [103]:
a = np.array([1, -2, 0])                                # 创建ndarray

a.cumprod()                                             # 计算累计乘积

array([ 1, -2,  0], dtype=int32)

### 3.4 逻辑运算

##### （24）逻辑且1
如果ndarray中每一个元素都为True，则返回True。

np.all函数与array.all方法等价。

In [104]:
np.array([True, False, False]).all()    

False

##### （25）逻辑或1
如果ndarray中有一个元素为True，则返回True。

np.any函数与array.any方法等价。

In [105]:
np.array([True, False, False]).any()    

True

##### （26）逻辑且2
对多个ndarray中每一个元素进行并列判断，如果并列的每一个元素全为True，则返回True。

In [106]:
a = np.array([True, False, True, False])            # 创建ndarray a
b = np.array([False, True, True, False])            # 创建ndarray b

In [107]:
np.logical_and(a, b)                                   # 进行逻辑且判断    

array([False, False,  True, False], dtype=bool)

##### （27）逻辑或2
对多个ndarray中的每一个元素进行并列判断， 如果并列的元素有一个为True，则返回True。

In [108]:
a = np.array([True, False, True, False])            # 创建ndarray a
b = np.array([False, True, True, False])            # 创建ndarray b

In [109]:
np.logical_or(a, b)    

array([ True,  True,  True, False], dtype=bool)

##### （28）np.where
对ndarray中每一个元素进行判断，如果满足条件，对于该元素返回第二个参数，不满足返回第三个参数。最后返回结果为ndarray。

常用于对数据条件判断后替换为其他值。

In [110]:
a = np.array([True, False, True])     # 创建ndarray a

np.where(a, 1, 0)        

array([1, 0, 1])

##### （29）广播


In [111]:
a = np.array([1, 3, 2, 4])              # 创建ndarray a

a + 2

array([3, 5, 4, 6])

 ---
### 4 数据操作

### 4.1 索引

##### （30）位置索引
根据位置获取ndarray的某一个值，使用方法类似list。

In [112]:
a = np.array([1,2,3,4])                 # 创建ndarray

a[2]                                    # 进行位置索引

3

##### （31）bool值索引
使用bool值进行索引，True则获取对应ndarray中的元素，False则不获取。最终返回ndarray。

In [113]:
a = np.array([1,2,3,4])                 # 创建ndarray

a[[True, False, True, False]]        # bool值索引

array([1, 3])

In [114]:
a[a > 2]                               # 常用bool值索引形式

array([3, 4])

### 4.2 数据规整化

##### （32）排序
对ndarray中元素进行排序，默认为升序排列。

np.sort函数和array.sort方法类似。

In [115]:
a = np.array([1,2,3,4])                 # 创建ndarray

a.sort()                                # 进行排序    
a

array([1, 2, 3, 4])

##### （33）维度调整
对ndarray中元素进行维度调整，调整为输入参数形状。

np.reshape函数和array.reshape方法等价。

In [116]:
a = np.array([1,2,3,4])                 # 创建ndarray

a.reshape(2,2)                      # 调整为2*2形式的ndarray


array([[1, 2],
       [3, 4]])

##### （34）转置
对ndarray进行转置。

np.transpose函数和array.T属性返回结果类似。

In [117]:
a = np.array([[1,2],[3,4]])                 # 创建ndarray

a.T                                     # 对a进行转置

array([[1, 3],
       [2, 4]])

##### （35）拼接
拼接多个ndarray。

axis=1表示横向拼接， axis=0表示纵向拼接

In [118]:
a =  np.array([[1,2], [3,4]])     # 创建ndarray

np.concatenate((a, a), axis=1)    # 拼接

array([[1, 2, 1, 2],
       [3, 4, 3, 4]])